AWSTemplateFormatVersion: "2010-09-09"
Description: EKS Microservices Infrastructure (Network, Compute, Security)

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod
    Description: Deployment environment name
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
  PublicSubnet1Cidr:
    Type: String
    Default: 10.0.1.0/24
  PublicSubnet2Cidr:
    Type: String
    Default: 10.0.2.0/24
  PrivateSubnet1Cidr:
    Type: String
    Default: 10.0.3.0/24
  PrivateSubnet2Cidr:
    Type: String
    Default: 10.0.4.0/24

Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: network/network.yaml
      Parameters:
        VpcCidr: !Ref VpcCidr
        PublicSubnet1Cidr: !Ref PublicSubnet1Cidr
        PublicSubnet2Cidr: !Ref PublicSubnet2Cidr
        PrivateSubnet1Cidr: !Ref PrivateSubnet1Cidr
        PrivateSubnet2Cidr: !Ref PrivateSubnet2Cidr
        Environment: !Ref Environment

  SecurityStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: security/security.yaml
      Parameters:
        VpcId: !GetAtt NetworkStack.Outputs.VPCId
        PublicSubnet1: !GetAtt NetworkStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt NetworkStack.Outputs.PublicSubnet2
        PrivateSubnet1: !GetAtt NetworkStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt NetworkStack.Outputs.PrivateSubnet2
        Environment: !Ref Environment

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: compute/compute.yaml
      Parameters:
        PrivateSubnet1: !GetAtt NetworkStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt NetworkStack.Outputs.PrivateSubnet2
        Environment: !Ref Environment
        ClusterSecurityGroupId: !GetAtt SecurityStack.Outputs.ClusterSecurityGroupId
    DependsOn: SecurityStack

Outputs:
  VPCId:
    Description: VPC ID from Network Stack
    Value: !GetAtt NetworkStack.Outputs.VPCId

  ClusterName:
    Description: EKS Cluster Name from Compute Stack
    Value: !GetAtt ComputeStack.Outputs.ClusterName
